# Artificial Neural Network

## Part 1 - Data Preprocessing

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [4]:
#Create dummy variables
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [5]:
## Concatenate the Data Frames

X=pd.concat([X,geography,gender],axis=1)

In [6]:
## Drop Unnecessary columns
X=X.drop(['Geography','Gender'],axis=1)

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Now let's make the ANN!

In [9]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [10]:
# Initialising the ANN
classifier = Sequential()

In [14]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(6, kernel_initializer = 'he_uniform',activation='relu',input_dim = 11)) # or units = 6
# output_dim = 6 gives error as parameters are updated now
# similarly for this, init = 'he_uniform' 

In [16]:
# Adding the second hidden layer
classifier.add(Dense(6, kernel_initializer = 'he_uniform',activation='relu'))

In [17]:
# Adding the output layer
classifier.add(Dense(1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))

In [18]:
# Compiling the ANN
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
# Fitting the ANN to the Training set
model_history=classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, epochs = 100)

# It's just epochs now. nb_epoch was deprecated years ago.

Epoch 1/100
536/536 [==============================] - 2s 2ms/step - loss: 0.6625 - accuracy: 0.6587 - val_loss: 0.5739 - val_accuracy: 0.7902
Epoch 2/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7955 - val_loss: 0.5305 - val_accuracy: 0.7944
Epoch 3/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7968 - val_loss: 0.5057 - val_accuracy: 0.7955
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7975 - val_loss: 0.4895 - val_accuracy: 0.8001
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.8003 - val_loss: 0.4776 - val_accuracy: 0.8058
Epoch 6/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.8043 - val_loss: 0.4686 - val_accuracy: 0.8076
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.8050 - val_loss: 0.4619 - val_accuracy: 0.8080

Epoch 58/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3766 - accuracy: 0.8365 - val_loss: 0.3983 - val_accuracy: 0.8239
Epoch 59/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3758 - accuracy: 0.8371 - val_loss: 0.3972 - val_accuracy: 0.8277
Epoch 60/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3752 - accuracy: 0.8378 - val_loss: 0.3968 - val_accuracy: 0.8277
Epoch 61/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3744 - accuracy: 0.8378 - val_loss: 0.3965 - val_accuracy: 0.8262
Epoch 62/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3739 - accuracy: 0.8356 - val_loss: 0.3952 - val_accuracy: 0.8289
Epoch 63/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3731 - accuracy: 0.8373 - val_loss: 0.3950 - val_accuracy: 0.8270
Epoch 64/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3721 - accuracy: 0.8356 - val_loss: 0.3944 - val_accuracy:

In [22]:
# list all data in history

print(model_history.history.keys())

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])


In [ ]:
# summarize history for accuracy
plt.plot(model_history.history['acc'])
plt.plot(model_history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
# summarize history for loss
plt.plot(model_history.history['loss'])
plt.plot(model_history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

## Part 3 - Making the predictions and evaluating the model

In [24]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [27]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1503,   92],
       [ 207,  198]], dtype=int64)

In [28]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
score

0.8505

## Part 4 - Hyperparameter Tuning

How to Select how many hidden layer and neurons in a neural network

In [ ]:
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [ ]:
#Create dummy variables
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [ ]:
## Concatenate the Data Frames

X=pd.concat([X,geography,gender],axis=1)

In [ ]:
## Drop Unnecessary columns
X=X.drop(['Geography','Gender'],axis=1)

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
## Perform Hyperparameter Optimization

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding, Flatten, LeakyReLU, BatchNormalization, Dropout
from keras.activations import relu, sigmoid
from keras.layers import LeakyReLU

In [ ]:
# def create_model(layers, activation):
#     model = Sequential()
#     for i, nodes in enumerate(layers):
#         if i==0:
#             model.add(Dense(nodes,input_dim=X_train.shape[1]))
#             model.add(Activation(activation))
#         else:
#             model.add(Dense(nodes))
#             model.add(Activation(activation))
#     model.add(Dense(1)) # Note: no activation beyond this point
    
#     model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
#     return model
    
# model = KerasClassifier(build_fn=create_model, verbose=0)

In [36]:
def create_model(layers, activation):
    model = Sequential()
    for i, nodes in enumerate(layers):
        if i==0:
            model.add(Dense(nodes,input_dim=X_train.shape[1]))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
            
    model.add(Dense(units = 1, kernel_initializer= 'glorot_uniform', activation = 'sigmoid')) # Note: no activation beyond this point
    
    model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
    return model
    
model = KerasClassifier(build_fn=create_model, verbose=0)

C:\Users\HARSHI~1\AppData\Local\Temp/ipykernel_25052/980714898.py:18: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  model = KerasClassifier(build_fn=create_model, verbose=0)


In [37]:
model

In [38]:
layers = [[20], [40, 20], [45, 30, 15]]
activations = ['sigmoid', 'relu']
param_grid = dict(layers=layers, activation=activations, batch_size = [128, 256], epochs=[30])
grid = GridSearchCV(estimator=model, param_grid=param_grid)

In [39]:
grid_result = grid.fit(X_train, y_train)

In [40]:
[grid_result.best_score_,grid_result.best_params_]

[0.8568750143051147,
 {'activation': 'relu', 'batch_size': 128, 'epochs': 30, 'layers': [40, 20]}]

In [41]:
pred_y = grid.predict(X_test)

In [42]:
y_pred = (pred_y > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [43]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1546,   49],
       [ 216,  189]], dtype=int64)

In [44]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
score

0.8675